console.log("✅ app.js chargé");
// =========================
// Config
// =========================
const WA_NUMBER = '33749723434';
const MAIL_TO   = 'contact@eternaweb.fr';

// Helpers rapides
const $  = (s, r=document)=>r.querySelector(s);
const $$ = (s, r=document)=>[...r.querySelectorAll(s)];
const isMobile = ()=>/Android|iPhone|iPad|iPod|Windows Phone/i.test(navigator.userAgent);

// =========================
const I18N = {
  fr: {
    'nav.menu':'Menu','nav.cv':'CV','nav.portfolio':'Portfolio','nav.vitrine':'Vitrine',
    'nav.tarifs':'Tarifs','nav.devis':'Vos consignes','nav.temoignages':'Témoignages',
    'hero.title':'EternaWeb','hero.subtitle':'CV & vitrines express — en ligne en 48 heures',
    'hero.lead':'✨ Un design premium, des intégrations rapides et un rendu clé en main.',
    'cta.whatsapp':'WhatsApp','cta.paypal':'PayPal',
    'services.h2':'🚀 Nos services',
'services.sub':'Choisissez un type de mini-site 👇',
'services.demo':'Voir le service',
'services.cv.desc':'Idéal pour les candidatures ou profils pros.',
'services.port.desc':'Parfait pour artistes & designers.',
'services.vit.desc':'Pour entreprises & indépendants.',
    'devis.h2': '📝 Vos consignes',
  'devis.sub': 'Choisissez, décrivez, envoyez — je reçois vos consignes.',
  'devis.type': 'Type de site',
  'devis.opt.cv': 'CV',
  'devis.opt.vitrine': 'Vitrine',
  'devis.opt.portfolio': 'Portfolio',
  'devis.opt.other': 'Autre',
  'devis.colors': 'Palette / couleurs',
  'devis.style': 'Style visuel',
  'devis.style1': 'Sobre & élégant',
  'devis.style2': 'Créatif & coloré',
  'devis.style3': 'Minimal & pro',
  'devis.style4': 'Nature & doux',
  'devis.integrations': 'Intégrations souhaitées',
  'devis.int.form': 'Formulaire contact',
  'devis.int.social': 'Réseaux sociaux',
  'devis.int.gallery': 'Galerie',
  'devis.other': 'Autres demandes',
  'devis.name': 'Prénom / Nom',
  'devis.email': 'Email',
  'devis.note': 'Aucun envoi serveur : votre logiciel e-mail s’ouvre avec le message prérempli.',
  'btn.fill': 'Vos consignes',
  'btn.send': 'Envoyer',
  'btn.choose': 'Je choisis cette formule',

     // PORTFOLIO
  'portfolio.section.title': '🎨 Modèles de Portfolio',
  'portfolio.section.desc': 'Idéal pour artistes, créateurs et designers.',
  'portfolio.pricing.title': '💼 Formules Portfolio',
  'portfolio.pricing.desc': 'Exposez vos créations avec élégance.',

    'portfolio.pack1.title': '📂 Pack Créatif – 29,99 €',
  'portfolio.pack1.li1': 'Mini-site (2–3 pages)',
  'portfolio.pack1.li2': 'Galerie photos/vidéos',
  'portfolio.pack1.li3': 'Présentation créateur',
  'portfolio.pack2.title': '🌟 Pack Premium – 59,99 €',
  'portfolio.pack2.li1': 'Tout le Pack Créatif',
  'portfolio.pack2.li2': 'Section blog',
  'portfolio.pack2.li3': 'Optimisation SEO',
  'portfolio.pack2.li4': 'Statistiques incluses',

     // CV
  'cv.section.title': '🚀 Nos formules CV',
  'cv.section.desc': 'Choisissez la formule adaptée à vos besoins.',
  'cv.pricing.title': '💼 Formules CV en ligne',
  'cv.pricing.desc': 'Mettez en valeur vos compétences avec un design clair et professionnel.',

  'cv.pack1.title': '📝 Pack Starter – 14,99 €',
  'cv.pack1.li1': 'Correction orthographique et grammaticale',
  'cv.pack1.li2': 'Mise en page simple et structurée (Word/PDF)',
  'cv.pack1.note': '👉 Idéal pour stage, job étudiant ou premier emploi',
  'cv.pack2.title': '🚀 Pack Boost – 29,99 €',
  'cv.pack2.li1': 'Tout le Pack Starter',
  'cv.pack2.li2': 'Optimisation du contenu (ATS friendly)',
  'cv.pack2.li3': 'Ajout de mots-clés stratégiques',
  'cv.pack2.li4': 'Pour une meilleure répétabilitépar les recruteurs',
  'cv.pack3.title': '🌐 Pack Premium – 59,99 €',
  'cv.pack3.li1': 'Tout le Pack Boost',
  'cv.pack3.li2': 'Création d’un CV en ligne (mini-site personnel)',
  'cv.pack3.li3': 'Hébergement inclus 1 an',
  'cv.pack3.li4': 'Design moderne (ordinateur & mobile)',
  'cv.pack3.li5': 'QR code intégré',
  'cv.pack3.li6': 'Pour vous démarquer face aux autres candidats',

    'testi.h2':'💬 Témoignages','testi.t1':'“Super réactive et professionnelle, mon site a été en ligne le jour même !”','testi.c1':'— Claire B.',
    'testi.t2':'“Design élégant, clair, et surtout… mes clients m’écrivent directement via WhatsApp !”','testi.c2':'— Malik T.',
    'testi.t3':'“Excellent rapport qualité/prix. Je recommande à 100 %.”','testi.c3':'— Sofia M.',
         'footer.faq':'FAQ',
    'faq.title': 'FAQ - EternaWeb',
'faq.h1': 'FAQ - EternaWeb',
'faq.q1': '✨ En combien de temps mon site est-il prêt ?',
'faq.a1': 'En général, en 1 heure maximum si toutes les infos sont prêtes !',
'faq.q2': '📲 Peut-on intégrer WhatsApp et PayPal ?',
'faq.a2': 'Oui, ton mini-site peut contenir des boutons directs pour commander.',
'faq.q3': '📄 Que dois-je fournir pour démarrer ?',
'faq.a3': 'Textes (ou points clés), 3–5 photos/logo, palette de couleurs, liens utiles (réseaux, Drive).',
'faq.q4': '🎨 Puis-je changer les couleurs et la mise en page ?',
'faq.a4': 'Oui, plusieurs allers-retours inclus pour ajuster style, couleurs et sections.',
'faq.q5': '🌐 Proposez-vous l’hébergement ?',
'faq.a5': 'Oui, hébergement inclus dans les formules (vitrine & premium). Migration possible.',
'faq.q6': '💡 Et si j’ai d’autres questions ?',
'faq.a6': 'Tu peux me les poser ci-dessous 👇',
'faq.labelEmail': 'Ton adresse e-mail :',
'faq.labelMsg': 'Ta question :',
'faq.btn': 'Envoyer la question',
'faq.back': '← Retour à l’accueil',
     'footer.about':'À propos',

// FAQ pour les CV
    faqCv: {
      title: 'FAQ – CV & mini-site CV - EternaWeb',
      h1: 'FAQ – CV & mini-site CV - EternaWeb',
'faqCv.q1': '✨ En combien de temps mon CV est-il prêt ?',
'faqCv.a1': 'En général sous 24 à 48 h, selon la formule choisie et la rapidité de réception des informations.',
'faqCv.q2': '📄 À qui s’adresse le service CV ?',
'faqCv.a2': 'Étudiants & jobs étudiants<br>Stages<br>Premier emploi<br>Reconversion professionnelle<br>Reprise d’activité<br>👉 Tous secteurs.',
'faqCv.q3': '📄 À qui s’adresse EternaWeb ?',
'faqCv.a3': 'Étudiants, chercheurs d’emploi, créateurs, freelances et entrepreneurs souhaitant une présence professionnelle moderne et efficace.',
'faqCv.q4': '⏱️ En combien de temps mon CV ou site est-il prêt ?',
'faqCv.a4': 'CV : 24 à 48h selon la formule.<br>Mini-site / portfolio : en moyenne 48h si les contenus sont fournis.',
'faqCv.q5': '🤖 Pourquoi parlez-vous d’optimisation ATS ?',
'faqCv.a5': 'Les recruteurs utilisent des logiciels de tri (ATS). J’intègre des mots-clés stratégiques pour améliorer la visibilité de ton CV auprès des recruteurs et des robots.',
'faqCv.q6': '📦 Quelles sont les formules CV ?',
'faqCv.a6': '<strong>Starter – 4,99 €</strong> : correction + mise en page structurée<br><strong>Boost – 9,99 €</strong> : optimisation ATS + mots-clés<br><strong>Premium – 19,99 €<[...]',
'faqCv.q7': '🌐 L’hébergement est-il inclus ?',
'faqCv.a7': 'Oui, hébergement inclus 1 an. Migration possible si besoin.',
'faqCv.q8': '💬 Puis-je demander des modifications ?',
'faqCv.a8': 'Oui, des ajustements sont inclus selon la formule choisie.',
'faqCv.q9': '💡 Une question spécifique ?',
'faqCv.a9': 'Tu peux me contacter directement ci-dessous 👇',
'faqCv.back': '← Retour à l’accueil'
    },
    
  "portfolio.title": "FAQ – Portfolio / Créateurs & Freelances - EternaWeb",
  "portfolio.h1": "FAQ – Portfolio / Créateurs & Freelances",
  "portfolio.q1": "✨ À qui s'adresse le portfolio ?",
  "portfolio.a1": "Créateurs<br>Freelances<br>Photographes<br>Artisans<br>Entrepreneurs<br>Marques personnelles",
  "portfolio.q2": "⏱️ En combien de temps mon portfolio est-il prêt ?",
  "portfolio.a2": "En moyenne 48 h, si tous les contenus sont fournis.",
  "portfolio.q3": "📦 Quelles sont les formules Portfolio ?",
  "portfolio.a3": "<strong>Pack Créatif – 29,99 €</strong><br>✔ Mini-site (2–3 pages)<br>✔ Galerie photos / vidéos<br>✔ Présentation du créateur<br><br><strong>Pack Premium – 59[...]",
  "portfolio.q4": "📊 Puis-je voir combien de personnes visitent mon site ?",
  "portfolio.a4": "Oui. Les statistiques de visites sont incluses dans le Pack Premium.",
  "portfolio.q5": "🎨 Puis-je personnaliser le design ?",
  "portfolio.a5": "Oui :<br>couleurs<br>style<br>structure<br>Le site est adapté à ton univers créatif.",
  "portfolio.q6": "🌍 L'hébergement est-il inclus ?",
  "portfolio.a6": "Oui, l'hébergement est inclus pendant 1 an. Migration possible si besoin.",
  "portfolio.q7": "📎 Que dois-je fournir ?",
  "portfolio.a7": "Textes ou idées<br>Photos / vidéos<br>Liens réseaux (si existants)",
  "portfolio.q8": "❓ Besoin d'un devis sur mesure ?",
  "portfolio.a8": "Un devis personnalisé est possible sur demande.",
  "portfolio.back": "← Retour à l’accueil",
    
       'about.title': 'À propos de EternaWeb',
  'about.p1': 'EternaWeb est né d’un besoin simple : permettre à chacun de présenter son projet, son talent ou son offre avec clarté et professionnalisme, même sans compétences techniques[...]',
  'about.p2': '✨ En 2 jours, votre vitrine ou votre CV en ligne peut voir le jour, avec un style épuré, humain et intuitif. Que vous soyez artisan, coach, artiste, thérapeute ou en recherche[...]',
  'about.missionTitle': 'Notre mission',
  'about.mission': 'Créer des sites simples, beaux et fonctionnels, pour révéler votre unicité au monde. Chez EternaWeb, on croit en la puissance du minimalisme allié à la bienveillance.',
  'about.targetTitle': 'À qui s’adresse EternaWeb ?',
  'about.li1': '• Aux artisans et créateurs qui veulent une vitrine douce et chaleureuse',
  'about.li2': '• Aux professionnels du bien-être en quête d’un espace simple et accueillant',
  'about.li3': '• Aux personnes en reconversion ou en recherche d’emploi, qui veulent un CV valorisant',
  'about.contact': '💌 Pour en savoir plus, discuter de votre projet ou demander un devis : <a href="mailto:contact@eternaweb.fr">contact@eternaweb.fr</a>',
  'about.back': '← Retour à l’accueil',
      'footer.legal':'Mentions légales',
  'legal.title': 'Mentions légales - EternaWeb',
'legal.h1': 'Mentions légales',
'legal.editorTitle': 'Éditeur du site',
'legal.editorText': '<strong>EternaWeb</strong><br>Danielle Kabongo<br>Email : <a href="mailto:contact.eternaweb@gmail.com">contact.eternaweb@gmail.com</a>',
'legal.hostTitle': 'Hébergement',
'legal.hostText': 'Le site est hébergé gratuitement par <strong>GitHub Pages</strong><br>GitHub Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, États-Unis<br>Site : <a href="https[...]',
'legal.respTitle': 'Responsabilité',
'legal.respText': 'L’éditeur met à disposition des informations et services dans le cadre de la création de mini-sites vitrines. Cependant, il ne saurait être tenu responsable des erreurs o[...]',
'legal.ipTitle': 'Propriété intellectuelle',
'legal.ipText': 'Les contenus (textes, images, logos) créés par EternaWeb sont protégés. Toute reproduction sans autorisation est interdite.',
'legal.back': '← Retour à l’accueil',
    'footer.privacy':'Confidentialité',
  'privacy.title': 'Confidentialité - EternaWeb',
'privacy.h1': 'Confidentialité',
'privacy.intro': 'La présente politique explique quelles données sont collectées lors de l’utilisation du site <strong>EternaWeb</strong>.',
'privacy.dataTitle': 'Données collectées',
'privacy.data1': 'Les données techniques collectées automatiquement par l’hébergeur GitHub (adresses IP, logs).',
'privacy.data2': 'Les informations transmises volontairement via les boutons de contact (WhatsApp, Instagram, Email, PayPal).',
'privacy.useTitle': 'Utilisation des données',
'privacy.useText': 'Les données sont utilisées uniquement pour permettre le bon fonctionnement du site et répondre aux demandes des utilisateurs. Aucune donnée n’est vendue ou transmise à [...]
'privacy.rightsTitle': 'Droits des utilisateurs',
'privacy.rightsText': 'Conformément au RGPD, vous pouvez demander l’accès, la rectification ou la suppression de vos données en contactant : <a href="mailto:contact.eternaweb@gmail.com">cont[...]',
'privacy.cookiesTitle': 'Cookies',
'privacy.cookiesText': 'Le site n’utilise pas de cookies publicitaires. Seuls des cookies techniques peuvent être générés par GitHub Pages ou par les services tiers utilisés (WhatsApp, Pay[...]',
'privacy.back': '← Retour à l’accueil',
     'footer.code':'Code de conduite',
  'code.title': 'Code de conduite - EternaWeb',
'code.h1': 'Code de conduite',
'code.intro': 'Chez <strong>EternaWeb</strong>, nous nous engageons à offrir un espace respectueux, sûr et bienveillant pour toutes et tous.',
'code.valuesTitle': '🌱 Nos valeurs fondamentales',
'code.value1': 'Respect mutuel, quelle que soit l’origine, l’identité ou les convictions',
'code.value2': 'Communication claire, douce et constructive',
'code.value3': 'Soutien et entraide dans les échanges',
'code.value4': 'Confidentialité des informations personnelles partagées',
'code.behaviorTitle': '🚫 Comportements inacceptables',
'code.behavior1': 'Tout type de harcèlement, intimidation ou langage discriminatoire',
'code.behavior2': 'Utilisation abusive des canaux de communication',
'code.behavior3': 'Partage non autorisé de données sensibles',
'code.engagementTitle': '🤝 Engagement de EternaWeb',
'code.engagement1': 'Nous nous réservons le droit de refuser tout projet ou échange qui ne respecte pas ce code de conduite.',
'code.engagement2': 'Nous encourageons chacun·e à faire preuve de courtoisie et à contribuer à une atmosphère de travail harmonieuse.',
'code.thanks': 'Merci d\'incarner l\'esprit EternaWeb : humain, éthique et inspiré ✨',
'code.back': '← Retour à l’accueil',
'footer.copy':'© 2025 EternaWeb — Tous droits réservés'
  },
en: {
    'nav.menu':'Menu','nav.cv':'CV','nav.portfolio':'Portfolio','nav.vitrine':'Showcase',
    'nav.tarifs':'Pricing','nav.devis':'Your brief','nav.temoignages':'Testimonials',
    'hero.title':'EternaWeb','hero.subtitle':'CV & showcase sites — online in 48 hours',
    'hero.lead':'✨ Premium design, fast integrations, and a turnkey result.',
    'cta.whatsapp':'WhatsApp','cta.paypal':'PayPal',
    'services.h2':'🚀 Our Services',
    'services.sub':'Choose your mini-site type 👇',
    'services.demo':'View service',
    'services.cv.desc':'Ideal for professional resumes.',
    'services.port.desc':'Perfect for artists & designers.',
    'services.vit.desc':'For businesses & freelancers.',
    'devis.h2': '📝 Your instructions',
  'devis.sub': 'Choose, describe, send — I receive your brief directly.',
  'devis.type': 'Type of site',
  'devis.opt.cv': 'CV',
  'devis.opt.vitrine': 'Showcase',
  'devis.opt.portfolio': 'Portfolio',
  'devis.opt.other': 'Other',
  'devis.colors': 'Palette / colors',
  'devis.style': 'Visual style',
  'devis.style1': 'Clean & elegant',
  'devis.style2': 'Creative & colorful',
  'devis.style3': 'Minimal & professional',
  'devis.style4': 'Natural & soft',
  'devis.integrations': 'Desired integrations',
  'devis.int.form': 'Contact form',
