/* Traductions propres à la nouvelle page CV. Ce fichier ne modifie pas les autres pages. */
const CV_I18N={
fr:{'cv.title':'Mes Modèles de CV','cv.intro':'Découvrez nos modèles : clairs, modernes et prêts à l’emploi.','cv.model1.title':'CV Structuré','cv.model1.text':'Une présentation professionnelle, claire et organisée, pensée pour les candidatures administratives, techniques et généralistes.','cv.model2.title':'CV Moderne','cv.model2.text':'Un CV présenté comme une véritable page professionnelle en ligne, accessible sur ordinateur comme sur mobile.','cv.preview':'Voir l’aperçu','cv.open':'Ouvrir la démo','cv.letter.title':'Lettre de motivation','cv.letter.text':'Une lettre personnalisée, cohérente avec votre CV et adaptée au poste visé.','cv.back':'⬅ Retour à l’accueil'},
en:{'cv.title':'My CV Templates','cv.intro':'Discover our templates: clear, modern and ready to use.','cv.model1.title':'Structured CV','cv.model1.text':'A clear and organized professional layout, designed for administrative, technical and general applications.','cv.model2.title':'Modern CV','cv.model2.text':'A CV presented as a professional online page, accessible on desktop and mobile.','cv.preview':'View preview','cv.open':'Open demo','cv.letter.title':'Cover Letter','cv.letter.text':'A personalized cover letter, consistent with your CV and tailored to the position.','cv.back':'⬅ Back to home'},
nl:{'cv.title':'Mijn CV-modellen','cv.intro':'Ontdek onze modellen: helder, modern en klaar voor gebruik.','cv.model1.title':'Gestructureerd CV','cv.model1.text':'Een heldere en georganiseerde professionele presentatie voor administratieve, technische en algemene sollicitaties.','cv.model2.title':'Modern CV','cv.model2.text':'Een CV als professionele online pagina, toegankelijk op desktop en mobiel.','cv.preview':'Voorbeeld bekijken','cv.open':'Demo openen','cv.letter.title':'Motivatiebrief','cv.letter.text':'Een persoonlijke motivatiebrief, afgestemd op je CV en de gewenste functie.','cv.back':'⬅ Terug naar home'},
et:{'cv.title':'Minu CV-mallid','cv.intro':'Tutvu meie selgete, kaasaegsete ja kasutusvalmis mallidega.','cv.model1.title':'Struktureeritud CV','cv.model1.text':'Selge ja korrastatud professionaalne vorm administratiivsetele, tehnilistele ja üldistele kandideerimistele.','cv.model2.title':'Moodne CV','cv.model2.text':'CV kui professionaalne veebileht, mida saab vaadata arvutis ja mobiilis.','cv.preview':'Vaata eelvaadet','cv.open':'Ava demo','cv.letter.title':'Motivatsioonikiri','cv.letter.text':'Isikupärastatud motivatsioonikiri, mis sobib kokku CV-ga ja sihitud ametikohaga.','cv.back':'⬅ Tagasi avalehele'},
ru:{'cv.title':'Мои шаблоны резюме','cv.intro':'Посмотрите наши шаблоны: понятные, современные и готовые к использованию.','cv.model1.title':'Структурированное резюме','cv.model1.text':'Чёткое и организованное профессиональное оформление для административных, технических и общих вакансий.','cv.model2.title':'Современное резюме','cv.model2.text':'Резюме в формате профессиональной онлайн-страницы для компьютера и мобильных устройств.','cv.preview':'Посмотреть','cv.open':'Открыть демо','cv.letter.title':'Сопроводительное письмо','cv.letter.text':'Персонализированное письмо, согласованное с резюме и адаптированное под вакансию.','cv.back':'⬅ На главную'},
de:{'cv.title':'Meine Lebenslauf-Vorlagen','cv.intro':'Entdecken Sie unsere klaren, modernen und einsatzbereiten Vorlagen.','cv.model1.title':'Strukturierter Lebenslauf','cv.model1.text':'Eine klare und geordnete professionelle Gestaltung für administrative, technische und allgemeine Bewerbungen.','cv.model2.title':'Moderner Lebenslauf','cv.model2.text':'Ein Lebenslauf als professionelle Online-Seite für Desktop und Mobilgeräte.','cv.preview':'Vorschau ansehen','cv.open':'Demo öffnen','cv.letter.title':'Motivationsschreiben','cv.letter.text':'Ein persönliches Motivationsschreiben, passend zu Ihrem Lebenslauf und zur gewünschten Stelle.','cv.back':'⬅ Zur Startseite'},
es:{'cv.title':'Mis modelos de CV','cv.intro':'Descubre nuestros modelos: claros, modernos y listos para usar.','cv.model1.title':'CV estructurado','cv.model1.text':'Una presentación profesional, clara y organizada para candidaturas administrativas, técnicas y generales.','cv.model2.title':'CV moderno','cv.model2.text':'Un CV presentado como una página profesional en línea, accesible desde ordenador y móvil.','cv.preview':'Ver vista previa','cv.open':'Abrir demo','cv.letter.title':'Carta de motivación','cv.letter.text':'Una carta personalizada, coherente con tu CV y adaptada al puesto.','cv.back':'⬅ Volver al inicio'},
it:{'cv.title':'I miei modelli di CV','cv.intro':'Scopri i nostri modelli: chiari, moderni e pronti all’uso.','cv.model1.title':'CV strutturato','cv.model1.text':'Una presentazione professionale, chiara e organizzata per candidature amministrative, tecniche e generali.','cv.model2.title':'CV moderno','cv.model2.text':'Un CV presentato come una vera pagina professionale online, accessibile da computer e mobile.','cv.preview':'Visualizza anteprima','cv.open':'Apri demo','cv.letter.title':'Lettera di motivazione','cv.letter.text':'Una lettera personalizzata, coerente con il CV e adatta alla posizione desiderata.','cv.back':'⬅ Torna alla home'}
};
function applyCvTranslations(){if(typeof I18N==='undefined')return;const lang=localStorage.getItem('eternaweb-lang')||localStorage.getItem('language')||'fr';const pack=CV_I18N[lang]||CV_I18N.fr;Object.assign(I18N[lang]||{},pack);document.querySelectorAll('[data-i18n]').forEach(el=>{const value=pack[el.dataset.i18n];if(value!==undefined)el.innerHTML=value;});}
applyCvTranslations();
