/* EternaWeb — complément néerlandais complet
   Corrige les éléments qui n'étaient pas reliés au dictionnaire principal.
   Le fichier ne touche aux textes que lorsque la langue active est nl.
*/
(function(){
  'use strict';

  const NL = {
    announce:'🚀 CV geleverd binnen 48–72 uur • Veilig betalen • WhatsApp-support',
    'nav.menu':'Menu','nav.cv':'CV','nav.devis':'Uw gegevens','nav.temoignages':'Getuigenissen',
    'hero.title':'EternaWeb','hero.subtitle':'Professioneel CV — klaar binnen 48 uur','hero.lead':'✨ Een premium ontwerp, snelle integratie en een volledig afgewerkt resultaat.',
    'cta.whatsapp':'WhatsApp','cta.paypal':'PayPal',
    'services.h2':'🚀 Onze diensten','services.sub':'Ontdek onze CV-oplossingen','services.cv':'📄 CV',
    'devis.h2':'📝 Uw gegevens','devis.sub':'Kies, beschrijf en verstuur — ik ontvang uw instructies.','devis.type':'Type CV','devis.opt.cv':'CV',
    'devis.colors':'Kleurenpalet / kleuren','devis.colorsPlaceholder':'Bijv. beige & goud, koffiebruin…','devis.style':'Visuele stijl','devis.style1':'Sober & elegant','devis.style2':'Creatief & kleurrijk','devis.style3':'Minimalistisch & professioneel','devis.style4':'Natuurlijk & zacht',
    'devis.plan':'Gekozen pakket','devis.planPlaceholder':'Kies een pakket vanaf de CV-pagina…','devis.integrations':'Gewenste opties','devis.int.pdf':'CV PDF','devis.int.online':'Online CV','devis.int.qr':'QR-code','devis.int.letter':'Motivatiebrief',
    'devis.file':'Voeg een CV, motivatiebrief of oud document toe','devis.fileHint':'Selecteer een PDF-, Word- of DOCX-bestand.','devis.drive':'Drive-link / reeds gedeeld document','devis.drivePlaceholder':'Plak hier uw Drive-link…','devis.other':'Andere verzoeken','devis.otherPlaceholder':'Wat u nog wilt verduidelijken…','devis.name':'Voornaam / achternaam','devis.namePlaceholder':'Uw naam','devis.email':'E-mail','devis.emailPlaceholder':'u@voorbeeld.com','devis.note':'Uw bericht wordt rechtstreeks naar EternaWeb verzonden',
    'btn.send':'Verzenden','btn.choose':'Ik kies dit pakket',
    'testi.h2':'💬 Getuigenissen','testi.t1':'“Super snel en professioneel, mijn site stond dezelfde dag online!”','testi.c1':'— Claire B.','testi.t2':'“Elegant en duidelijk ontwerp; mijn klanten kunnen mij rechtstreeks via WhatsApp schrijven!”','testi.c2':'— Malik T.','testi.t3':'“Uitstekende prijs-kwaliteitverhouding. Ik raad het 100% aan.”','testi.c3':'— Sofia M.',
    'footer.faq':'FAQ','footer.contact':'💬 Contact opnemen','footer.about':'Over ons','footer.legal':'Juridische informatie','footer.privacy':'Privacy','footer.code':'Gedragscode','footer.copy':'© 2025 EternaWeb — Alle rechten voorbehouden',

    'faq.title':'FAQ - EternaWeb','faq.h1':'FAQ - EternaWeb','faq.q1':'✨ Hoe snel is mijn site klaar?','faq.a1':'Over het algemeen is uw online CV binnen 48 tot 72 uur klaar, op voorwaarde dat alle benodigde informatie is ontvangen.','faq.q2':'📲 Kunnen WhatsApp en PayPal worden geïntegreerd?','faq.a2':'Ja, uw online CV kan directe knoppen naar WhatsApp en PayPal bevatten, afhankelijk van uw behoeften.','faq.q3':'📄 Wat moet ik aanleveren om te beginnen?','faq.a3':'Vul het formulier in bij «Uw gegevens». Daar vindt u alle informatie die nodig is om uw online CV voor te bereiden.','faq.q4':'🎨 Kan ik de kleuren en lay-out wijzigen?','faq.a4':'Ja. U kunt de achtergrondkleur aanpassen of een afbeelding als achtergrond toevoegen, zodat uw CV bij uw stijl past.','faq.q5':'🌐 Bieden jullie hosting aan?','faq.a5':'Ja. Hosting is 1 jaar inbegrepen in het Premium-pakket.','faq.q6':'💡 En als ik nog andere vragen heb?','faq.a6':'U kunt ze hieronder stellen 👇','faq.labelEmail':'Uw e-mailadres:','faq.labelMsg':'Uw vraag:','faq.btn':'Vraag verzenden','faq.back':'← Terug naar de homepagina',
    'faqCv.title':'FAQ – CV & online CV - EternaWeb','faqCv.h1':'FAQ – CV & online CV - EternaWeb','faqCv.q1':'✨ Hoe snel is mijn CV klaar?','faqCv.a1':'Over het algemeen binnen 24 tot 48 uur, afhankelijk van het gekozen pakket en de ontvangst van de benodigde informatie.','faqCv.q2':'📄 Voor wie is de CV-service bedoeld?','faqCv.a2':'De CV-service is onder andere bedoeld voor studenten,<br>werkzoekenden,<br>kandidaten voor een eerste baan,<br>mensen die van beroep veranderen of opnieuw aan het werk gaan.<br>👉 Alle sectoren.','faqCv.q3':'📄 Voor wie is EternaWeb bedoeld?','faqCv.a3':'EternaWeb helpt studenten, werkzoekenden, makers, freelancers en ondernemers die hun profiel of activiteit op een professionele en moderne manier willen presenteren.','faqCv.q4':'🤖 Waarom spreken jullie over ATS-optimalisatie?','faqCv.a4':'Recruiters gebruiken software die ATS (Applicant Tracking Systems) wordt genoemd om sollicitaties te sorteren. Optimalisatie betekent dat relevante zoekwoorden en een geschikte structuur worden toegevoegd, zodat uw CV beter door deze systemen wordt gelezen en zichtbaarder wordt.','faqCv.q5':'📦 Welke CV-pakketten zijn er?','faqCv.a5':'<strong>Starter – 14,99 €</strong> : correctie + gestructureerde opmaak<br><strong>Boost – 29,99 €</strong> : ATS-optimalisatie + strategische zoekwoorden<br><strong>Premium – 59,99 €</strong> : CV + online CV + QR-code + 1 jaar hosting<br><strong>Motivatiebrief – 7,99 €</strong> : professionele structuur + argumentatie + aanpassing aan de vacature + correctie + levering in Word/PDF','faqCv.q6':'🌐 Is hosting inbegrepen?','faqCv.a6':'Ja. Hosting van het online CV is 1 jaar inbegrepen in het Premium-pakket.','faqCv.q7':'💬 Kan ik wijzigingen aanvragen?','faqCv.a7':'Ja, aanpassingen zijn inbegrepen afhankelijk van het gekozen pakket. De voorwaarden kunnen per pakket verschillen.','faqCv.q8':'💡 Een specifieke vraag?','faqCv.a8':'U kunt rechtstreeks contact met ons opnemen via het onderstaande contactformulier 👇','faqCv.back':'← Terug naar de homepagina',

    'about.title':'Over EternaWeb','about.p1':'EternaWeb is ontstaan vanuit een eenvoudig idee: iedereen helpen om zijn of haar profiel, activiteit, project of talent duidelijk en professioneel te presenteren, zonder technische kennis nodig te hebben.','about.p2':'✨ EternaWeb biedt toegankelijke en persoonlijke oplossingen: professionele CV’s, online CV’s en motivatiebrieven. Elke realisatie is helder, modern, responsive en afgestemd op de gebruiker.','about.missionTitle':'Onze missie','about.mission':'Eenvoudige, elegante en nuttige digitale oplossingen creëren waarmee iedereen zich beter kan presenteren en meer zichtbaarheid kan krijgen.<br>Bij EternaWeb geloven we dat een professionele online aanwezigheid niet ingewikkeld of ontoegankelijk hoeft te zijn.','about.targetTitle':'Voor wie is EternaWeb bedoeld?','about.li1':'• Voor mensen die werk zoeken, zich omscholen of op zoek zijn naar een eerste baan','about.li2':'• Voor studenten die hun profiel en vaardigheden willen versterken','about.li3':'• Voor ambachtslieden, makers en ondernemers die hun activiteit willen presenteren','about.li4':'• Voor freelancers en professionals die hun online aanwezigheid willen ontwikkelen','about.li5':'• Voor iedereen die een modern, professioneel en persoonlijk CV wil hebben.','about.contact':'💌 Meer weten, uw project bespreken of een offerte aanvragen: <a href="mailto:eternaweb.contact@gmail.com">eternaweb.contact@gmail.com</a>','about.back':'← Terug naar de homepagina',

    'legal.title':'Juridische informatie - EternaWeb','legal.h1':'Juridische informatie','legal.editorTitle':'Websitebeheerder','legal.editorText':'<strong>EternaWeb</strong><br>Danielle Kabongo<br>E-mail: <a href="mailto:eternaweb.contact@gmail.com">eternaweb.contact@gmail.com</a>','legal.hostTitle':'Hosting','legal.hostText':'De website wordt gratis gehost door <strong>GitHub Pages</strong><br>GitHub Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, Verenigde Staten<br>Website: <a href="https://pages.github.com/" target="_blank">pages.github.com</a>','legal.respTitle':'Aansprakelijkheid','legal.respText':'De beheerder stelt informatie en diensten beschikbaar voor professionele CV’s, online CV’s en motivatiebrieven. De beheerder kan echter niet verantwoordelijk worden gehouden voor fouten of onbeschikbaarheid van de website.','legal.ipTitle':'Intellectuele eigendom','legal.ipText':'De inhoud (teksten, afbeeldingen en logo’s) die door EternaWeb is gemaakt, is beschermd. Elke reproductie zonder toestemming is verboden.','legal.back':'← Terug naar de homepagina',

    'privacy.title':'Privacy - EternaWeb','privacy.h1':'Privacy','privacy.intro':'Dit beleid legt uit welke gegevens worden verzameld bij het gebruik van de website <strong>EternaWeb</strong>.','privacy.dataTitle':'Verzamelde gegevens','privacy.data1':'Technische gegevens die automatisch door de hostingprovider GitHub worden verzameld (IP-adressen, logs).','privacy.data2':'Informatie die vrijwillig wordt verstrekt via de contactknoppen (WhatsApp, Instagram, e-mail, PayPal).','privacy.useTitle':'Gebruik van gegevens','privacy.useText':'De gegevens worden uitsluitend gebruikt om de website goed te laten functioneren en om verzoeken van gebruikers te beantwoorden. Geen gegevens worden verkocht of doorgegeven aan derden, behalve aan technische dienstverleners (GitHub, WhatsApp, PayPal, Instagram).','privacy.rightsTitle':'Rechten van gebruikers','privacy.rightsText':'Volgens de AVG kunt u toegang tot, correctie van of verwijdering van uw gegevens vragen door contact op te nemen via: <a href="mailto:eternaweb.contact@gmail.com">eternaweb.contact@gmail.com</a>','privacy.cookiesTitle':'Cookies','privacy.cookiesText':'De website gebruikt geen advertentiecookies. Alleen technische cookies kunnen worden gegenereerd door GitHub Pages of de gebruikte diensten van derden (WhatsApp, PayPal, Instagram).','privacy.back':'← Terug naar de homepagina',

    'code.title':'Gedragscode - EternaWeb','code.h1':'Gedragscode','code.intro':'Bij <strong>EternaWeb</strong> zetten we ons in voor een respectvolle, veilige en vriendelijke omgeving voor iedereen.','code.valuesTitle':'🌱 Onze kernwaarden','code.value1':'Wederzijds respect, ongeacht afkomst, identiteit of overtuigingen','code.value2':'Duidelijke, vriendelijke en constructieve communicatie','code.value3':'Ondersteuning en wederzijdse hulp in de communicatie','code.value4':'Vertrouwelijkheid van gedeelde persoonlijke informatie','code.behaviorTitle':'🚫 Onacceptabel gedrag','code.behavior1':'Elke vorm van intimidatie, pesterij of discriminerende taal','code.behavior2':'Misbruik van communicatiekanalen','code.behavior3':'Onbevoegd delen van gevoelige gegevens','code.engagementTitle':'🤝 Engagement van EternaWeb','code.engagement1':'We behouden ons het recht voor om elk project of gesprek te weigeren dat deze gedragscode niet respecteert.','code.engagement2':'We moedigen iedereen aan beleefd te zijn en bij te dragen aan een harmonieuze werkomgeving.','code.thanks':'Bedankt dat u de EternaWeb-geest belichaamt: menselijk, ethisch en geïnspireerd ✨','code.back':'← Terug naar de homepagina',

    'cv.title':'Mijn CV-modellen','cv.intro':'Ontdek onze modellen: helder, modern en klaar voor gebruik.','cv.model1.title':'Gestructureerd CV','cv.model1.text':'Een heldere en georganiseerde professionele presentatie voor administratieve, technische en algemene sollicitaties.','cv.model2.title':'Modern CV','cv.model2.text':'Een CV als professionele online pagina, toegankelijk op computer en mobiel.','cv.preview':'Voorbeeld bekijken','cv.open':'Demo openen','cv.letter.title':'Persoonlijke motivatiebrief','cv.letter.text':'Een persoonlijke motivatiebrief, afgestemd op uw CV en op de functie waarop u solliciteert.','cv.pricing.h2':'💼 CV-pakketten','cv.pricing.sub':'Professionele CV-oplossingen, aangepast aan uw behoeften.','cv.pack1.title':'📝 Pack Starter – 14,99 €','cv.pack1.li1':'Spelling- en grammaticacontrole','cv.pack1.li2':'Eenvoudige en gestructureerde opmaak (Word/PDF)','cv.pack1.note':'👉 Ideaal voor stage, studentenjob of eerste baan','cv.pack2.title':'🚀 Pack Boost – 29,99 €','cv.pack2.li1':'Inclusief alle functies van Pack Starter','cv.pack2.li2':'Optimalisatie van de inhoud (ATS-vriendelijk)','cv.pack2.li3':'Toevoeging van strategische zoekwoorden','cv.pack2.li4':'Voor een betere zichtbaarheid bij recruiters','cv.pack3.title':'🌐 Pack Premium – 59,99 €','cv.pack3.li1':'Inclusief alle functies van Pack Boost','cv.pack3.li2':'Creatie van een online CV (persoonlijke miniwebsite)','cv.pack3.li3':'1 jaar hosting inbegrepen','cv.pack3.li4':'Modern design (computer & mobiel)','cv.pack3.li5':'Geïntegreerde QR-code','cv.pack3.li6':'Om u te onderscheiden van andere kandidaten','cv.pack4.title':'📄 Persoonlijke motivatiebrief – 7,99 €','cv.pack4.li1':'Professionele structuur','cv.pack4.li2':'Duidelijke en overtuigende argumentatie','cv.pack4.li3':'Aanpassing aan de vacature','cv.pack4.li4':'Spelling- en grammaticacontrole','cv.pack4.li5':'Levering in Word/PDF','cv.back':'⬅ Terug naar de homepagina'
  };

  function activeLang(){
    return (localStorage.getItem('eternaweb-lang') || localStorage.getItem('language') || document.documentElement.lang || 'fr').toLowerCase().slice(0,2);
  }

  function apply(){
    if(activeLang()!=='nl') return;
    document.querySelectorAll('[data-i18n]').forEach(function(el){
      const k=el.getAttribute('data-i18n');
      if(Object.prototype.hasOwnProperty.call(NL,k)) el.innerHTML=NL[k];
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(function(el){
      const k=el.getAttribute('data-i18n-placeholder');
      if(Object.prototype.hasOwnProperty.call(NL,k)) el.setAttribute('placeholder',NL[k]);
    });
    document.documentElement.lang='nl';

    document.querySelectorAll('.showcase-kicker').forEach(function(el,i){
      el.textContent=['CV professioneel','Online CV','Sollicitatie'][i] || el.textContent;
    });
    document.querySelectorAll('[data-preview-title]').forEach(function(el){
      const v=el.getAttribute('data-preview-title');
      if(v==='CV Structuré') el.setAttribute('data-preview-title','Gestructureerd CV');
      if(v==='CV Moderne') el.setAttribute('data-preview-title','Modern CV');
      if(v==='Lettre de motivation') el.setAttribute('data-preview-title','Motivatiebrief');
    });
    document.querySelectorAll('footer .footer-contact:not([data-i18n])').forEach(function(el){el.innerHTML=NL['footer.contact'];});
  }

  let last='';
  function tick(){
    const lang=activeLang();
    if(lang!==last || lang==='nl'){ last=lang; apply(); }
  }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',tick); else tick();
  setInterval(tick,500);
  window.addEventListener('storage',tick);
})();
